---
title: "arachidonic acid"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DiagrammeR)
```

Example
```{r}
grViz(diagram = "digraph flowchart {
      # define node aesthetics
      node [fontname = Arial, shape = oval, color = Lavender, style = filled]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
# set up node layout
      tab1 -> tab2;
      tab2 -> tab3;
      tab2 -> tab4
      }
[1]: 'Learning Data Science'
      [2]: 'Industry vs Technical Knowledge'
      [3]: 'Python/R'
      [4]: 'Domain Experience'
      ")
```

lavender= identified
yellow = not identified
```{r}
grViz(diagram = "digraph flowchart {
      # define node aesthetics
      node [fontname = Arial, shape = oval, color = Lavender, style = filled]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
      tab6 [label = '@@6']
      tab7 [label = '@@7']
      tab8 [label = '@@8']
      tab9 [label = '@@9', color = yellow]
      tab10 [label = '@@10']
      tab11 [label = '@@11']
      tab12 [label = '@@12']
      tab13 [label = '@@13']
      tab14 [label = '@@14']
      tab15 [label = '@@15']
      tab16 [label = '@@16']
      tab17 [label = '@@17']
      tab18 [label = '@@18']
      tab19 [label = '@@19']
      tab20 [label = '@@20']
      tab21 [label = '@@21']
      tab22 [label = '@@22']
      tab23 [label = '@@23']
      tab24 [label = '@@24']
      tab25 [label = '@@25']
      tab26 [label = '@@26']
      tab27 [label = '@@27']
      tab28 [label = '@@28']
      tab29 [label = '@@29', color = yellow]
      tab30 [label = '@@30', color = yellow]
      tab31 [label = '@@31', color = yellow]
      tab32 [label = '@@32', color = yellow]
      tab33 [label = '@@33', color = yellow]
      tab34 [label = '@@34', color = yellow]
      tab35 [label = '@@35']
      tab36 [label = '@@36']
# set up node layout
      tab1 -> tab2;
      tab2 -> tab3;
      tab2 -> tab4;
      tab2 -> tab5;
      tab2 -> tab6;
      tab2 -> tab7;
      tab2 -> tab8;
      tab2 -> tab9;
      tab2 -> tab10;
      tab2 -> tab11;
      tab2 -> tab12;
      tab2 -> tab13;
      tab2 -> tab14;
      tab3 -> tab15;
      tab4 -> tab16;
      tab5 -> tab17;
      tab6 -> tab18;
      tab7 -> tab19;
      tab19 -> tab20;
      tab7 -> tab21;
      tab21 -> tab22;
      tab7 -> tab23;
      tab8 -> tab24;
      tab8 -> tab25;
      tab24 -> tab26;
      tab24 -> tab27;
      tab26 -> tab28;
      tab27 -> tab29;
      tab9 -> tab30;
      tab30 -> tab31;
      tab30 -> tab32;
      tab30 -> tab33;
      tab30 -> tab34;
      tab31 -> tab35;
      tab32 -> tab36;
      tab30 -> tab36
      }
[1]: 'C00157: Phosphatidylcholine'
      [2]: 'C00219: Arachidonic Acid'
      [3]: 'C14768'
      [4]: 'C14769'
      [5]: 'C14770'
      [6]: 'C14771'
      [7]: 'C05966'
      [8]: 'C05356'
      [9]: 'C05956'
      [10]: 'C14823'
      [11]: 'C14812'
      [12]: 'C14748'
      [13]: 'C14749'
      [14]: 'C05965'
      [15]: 'C14772'
      [16]: 'C14773'
      [17]: 'C14774'
      [18]: 'C14775'
      [19]: 'C14781'
      [20]: 'C14782'
      [21]: 'C14813'
      [22]: 'C14814'
      [23]: 'C04742'
      [24]: 'C00909'
      [25]: 'C04805'
      [26]: 'C02165'
      [27]: 'C02166'
      [28]: 'C04853'
      [29]: 'C05951'
      [30]: 'C00427'
      [31]: 'C00696'
      [32]: 'C00584'
      [33]: 'C01312'
      [34]: 'C02198'
      [35]: 'C05959'
      [36]: 'C00639'
      
      ")
```

```{r}
grViz(diagram = "digraph flowchart {
      # define node aesthetics
      graph [layout = dot,
       rankdir = LR]
      node [fontname = Arial, shape = oval, color = Lavender, style = filled]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
      tab6 [label = '@@6']
      tab7 [label = '@@7']
      tab8 [label = '@@8']
      tab9 [label = '@@9', color = yellow]
      tab10 [label = '@@10']
      tab11 [label = '@@11']
      tab12 [label = '@@12']
      tab13 [label = '@@13']
      tab14 [label = '@@14']
      tab15 [label = '@@15']
      tab16 [label = '@@16']
      tab17 [label = '@@17']
      tab18 [label = '@@18']
      tab19 [label = '@@19']
      tab20 [label = '@@20']
      tab21 [label = '@@21']
      tab22 [label = '@@22']
      tab23 [label = '@@23']
      tab24 [label = '@@24']
      tab25 [label = '@@25']
      tab26 [label = '@@26']
      tab27 [label = '@@27']
      tab28 [label = '@@28']
      tab29 [label = '@@29', color = yellow]
      tab30 [label = '@@30', color = yellow]
      tab31 [label = '@@31', color = yellow]
      tab32 [label = '@@32', color = yellow]
      tab33 [label = '@@33', color = yellow]
      tab34 [label = '@@34', color = yellow]
      tab35 [label = '@@35']
      tab36 [label = '@@36']
# set up node layout
      tab1 -> tab2;
      tab2 -> tab3;
      tab2 -> tab4;
      tab2 -> tab5;
      tab2 -> tab6;
      tab2 -> tab7;
      tab2 -> tab8;
      tab2 -> tab9;
      tab2 -> tab10;
      tab2 -> tab11;
      tab2 -> tab12;
      tab2 -> tab13;
      tab2 -> tab14;
      tab3 -> tab15;
      tab4 -> tab16;
      tab5 -> tab17;
      tab6 -> tab18;
      tab7 -> tab19;
      tab19 -> tab20;
      tab7 -> tab21;
      tab21 -> tab22;
      tab7 -> tab23;
      tab8 -> tab24;
      tab8 -> tab25;
      tab24 -> tab26;
      tab24 -> tab27;
      tab26 -> tab28;
      tab27 -> tab29;
      tab9 -> tab30;
      tab30 -> tab31;
      tab30 -> tab32;
      tab30 -> tab33;
      tab30 -> tab34;
      tab31 -> tab35;
      tab32 -> tab36;
      tab30 -> tab36
      }
[1]: 'C00157: Phosphatidylcholine'
      [2]: 'C00219: Arachidonic Acid'
      [3]: 'C14768: 5,6-EET'
      [4]: 'C14769: 8,9-EET'
      [5]: 'C14770: 11,12-EET'
      [6]: 'C14771: 14,15-EET'
      [7]: 'C05966: 15(S)-HPETE'
      [8]: 'C05356: 5(S)-HPETE'
      [9]: 'C05956: Prostaglandin G2;'
      [10]: 'C14823: 8(S)-HPETE'
      [11]: 'C14812: 12(R)-HPETE'
      [12]: 'C14748: 20-HETE'
      [13]: 'C14749: 19(S)-HETE'
      [14]: 'C05965: 12(S)-HPETE'
      [15]: 'C14772: 5,6-DHET'
      [16]: 'C14773: 8,9-DHET'
      [17]: 'C14774: 11,12-DHET'
      [18]: 'C14775: 14,15-DHET'
      [19]: 'C14781: 15H-11,12-EETA'
      [20]: 'C14782: 11,12,15-THETA'
      [21]: 'C14813: 11H-14,15-EETA'
      [22]: 'C14814: 11,14,15-THETA'
      [23]: 'C04742: 15(S)-HETE'
      [24]: 'C00909: Leukotriene A4'
      [25]: 'C04805: 5(S)-HETE'
      [26]: 'C02165: Leukotriene B4'
      [27]: 'C02166: Leukotriene C4'
      [28]: 'C04853: 20-OH-Leukotriene B4'
      [29]: 'C05951: Leukotriene D4'
      [30]: 'C00427: Prostaglandin H2'
      [31]: 'C00696: Prostaglandin D2'
      [32]: 'C00584: Prostaglandin E2'
      [33]: 'C01312: Prostaglandin I2'
      [34]: 'C02198: Thromboxane A2'
      [35]: 'C05959: 11-epi-Prostaglandin F2alpha'
      [36]: 'C00639: Prostaglandin F2alpha'
      
      ")
```

```{r}
grViz(diagram = "digraph flowchart {
      # define node aesthetics
      node [fontname = Arial, shape = oval, color = Lavender, style = filled]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
      tab6 [label = '@@6']
      tab7 [label = '@@7']
      tab8 [label = '@@8']
      tab9 [label = '@@9', color = yellow]
      tab10 [label = '@@10']
      tab11 [label = '@@11']
      tab12 [label = '@@12']
      tab13 [label = '@@13']
      tab14 [label = '@@14']
      tab15 [label = '@@15']
      tab16 [label = '@@16']
      tab17 [label = '@@17']
      tab18 [label = '@@18']
      tab19 [label = '@@19']
      tab20 [label = '@@20']
      tab21 [label = '@@21']
      tab22 [label = '@@22']
      tab23 [label = '@@23']
      tab24 [label = '@@24']
      tab25 [label = '@@25']
      tab26 [label = '@@26']
      tab27 [label = '@@27']
      tab28 [label = '@@28']
      tab29 [label = '@@29', color = yellow]
      tab30 [label = '@@30', color = yellow]
      tab31 [label = '@@31', color = yellow]
      tab32 [label = '@@32', color = yellow]
      tab33 [label = '@@33', color = yellow]
      tab34 [label = '@@34', color = yellow]
      tab35 [label = '@@35']
      tab36 [label = '@@36']
# set up node layout
      tab1 -> tab2;
      tab2 -> tab3;
      tab2 -> tab4;
      tab2 -> tab5;
      tab2 -> tab6;
      tab2 -> tab7;
      tab2 -> tab8;
      tab2 -> tab9;
      tab2 -> tab10;
      tab2 -> tab11;
      tab2 -> tab12;
      tab2 -> tab13;
      tab2 -> tab14;
      tab3 -> tab15;
      tab4 -> tab16;
      tab5 -> tab17;
      tab6 -> tab18;
      tab7 -> tab19;
      tab19 -> tab20;
      tab7 -> tab21;
      tab21 -> tab22;
      tab7 -> tab23;
      tab8 -> tab24;
      tab8 -> tab25;
      tab24 -> tab26;
      tab24 -> tab27;
      tab26 -> tab28;
      tab27 -> tab29;
      tab9 -> tab30;
      tab30 -> tab31;
      tab30 -> tab32;
      tab30 -> tab33;
      tab30 -> tab34;
      tab31 -> tab35;
      tab32 -> tab36;
      tab30 -> tab36
      }
[1]: 'C00157: Phosphatidylcholine'
      [2]: 'C00219: Arachidonic Acid'
      [3]: 'C14768: 5,6-EET'
      [4]: 'C14769: 8,9-EET'
      [5]: 'C14770: 11,12-EET'
      [6]: 'C14771: 14,15-EET'
      [7]: 'C05966: 15(S)-HPETE'
      [8]: 'C05356: 5(S)-HPETE'
      [9]: 'C05956: Prostaglandin G2;'
      [10]: 'C14823: 8(S)-HPETE'
      [11]: 'C14812: 12(R)-HPETE'
      [12]: 'C14748: 20-HETE'
      [13]: 'C14749: 19(S)-HETE'
      [14]: 'C05965: 12(S)-HPETE'
      [15]: 'C14772: 5,6-DHET'
      [16]: 'C14773: 8,9-DHET'
      [17]: 'C14774: 11,12-DHET'
      [18]: 'C14775: 14,15-DHET'
      [19]: 'C14781: 15H-11,12-EETA'
      [20]: 'C14782: 11,12,15-THETA'
      [21]: 'C14813: 11H-14,15-EETA'
      [22]: 'C14814: 11,14,15-THETA'
      [23]: 'C04742: 15(S)-HETE'
      [24]: 'C00909: Leukotriene A4'
      [25]: 'C04805: 5(S)-HETE'
      [26]: 'C02165: Leukotriene B4'
      [27]: 'C02166: Leukotriene C4'
      [28]: 'C04853: 20-OH-Leukotriene B4'
      [29]: 'C05951: Leukotriene D4'
      [30]: 'C00427: Prostaglandin H2'
      [31]: 'C00696: Prostaglandin D2'
      [32]: 'C00584: Prostaglandin E2'
      [33]: 'C01312: Prostaglandin I2'
      [34]: 'C02198: Thromboxane A2'
      [35]: 'C05959: 11-epi-Prostaglandin F2alpha'
      [36]: 'C00639: Prostaglandin F2alpha'
      
      ")
```