---
title: "explore CCA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sRDA)
```


```{r}
dataXY <- generate_data(nr_LVs = 2,
                           n = 250,
                           nr_correlated_Xs = c(5,20),
                           nr_uncorrelated_Xs = 250,
                           mean_reg_weights_assoc_X =
                             c(0.9,0.5),
                           sd_reg_weights_assoc_X =
                             c(0.05, 0.05),
                           Xnoise_min = -0.3,
                           Xnoise_max = 0.3,
                           nr_correlated_Ys = c(10,15),
                           nr_uncorrelated_Ys = 350,
                           mean_reg_weights_assoc_Y =
                             c(0.9,0.6),
                           sd_reg_weights_assoc_Y =
                             c(0.05, 0.05),
                           Ynoise_min = -0.3,
                           Ynoise_max = 0.3)

# seperate predictor and predicted sets
X <- dataXY$X
Y <- dataXY$Y

# run sRDA
CCA.res <- sCCA(predictor = X, predicted = Y, nonzero = 5,
ridge_penalty = 1, penalization = "ust")


# check first 10 weights of X
CCA.res$ALPHA[1:10]

## Not run: 
# run sRDA with cross-validation to determine best penalization parameters
CCA.res <- sCCA(predictor = X, predicted = Y, nonzero = c(5,10,15),
ridge_penalty = c(0.1,1), penalization = "enet", cross_validate = TRUE,
parallel_CV = TRUE)

# check first 10 weights of X
CCA.res$ALPHA[1:10]
CCA.res$ridge_penalty
CCA.res$nr_nonzeros

# obtain multiple latent variables
CCA.res <- sCCA(predictor = X, predicted = Y, nonzero = c(5,10,15),
ridge_penalty = c(0.1,1), penalization = "enet", cross_validate = TRUE,
parallel_CV = TRUE, multiple_LV = TRUE, nr_LVs = 2, max_iterations = 5)

# check first 10 weights of X in first two component
CCA.res$ALPHA[[1]][1:10]
CCA.res$ALPHA[[2]][1:10]

# latent variables are orthogonal to each other
t(CCA.res$XI[[1]]) %*% CCA.res$XI[[2]]
```

# CCA Package
```{r}
library(CCA)
```

https://www.jstatsoft.org/article/view/v023i12
```{r}
load("../data/all_fe_30DPI")
load("../data/all_fe_12week")

all_fe_30DPI
all_fe_12week

all_fe <- rbind(all_fe_12week, all_fe_30DPI)

single_expression <- all_fe %>%
  gather(key = marker, value = expression, -filename, -cell_no, -total_count_by_file, -percentage)%>%
  group_by(filename, marker, expression) %>%
  summarise(cells_per_marker = sum(cell_no)) %>%
  ungroup() %>%
  group_by(filename, marker) %>%
  mutate(total_cells = sum(cells_per_marker),
         percent_per_marker = 100*cells_per_marker/total_cells) %>%
  ungroup() %>%
  mutate(timepoint = str_extract(filename, "[:alpha:]+[:digit:]+"),
         filename = str_extract(filename, "Pig [0-9]*")) %>%
  mutate(vaccine_status = ifelse(filename == "Pig 9947" | filename == "Pig 1817" | filename == "Pig 6059" | filename == "Pig 4515"| filename == "Pig 5273", "vaccinated", "control"))



metabolites <- read.csv("../data/peakTable_Minipig_Vaccinated_Unvaccinated_QC.csv") %>%
  dplyr::rename(metaboliteID = X) %>%
  select(metaboliteID, contains("Minipig")) %>%
  pivot_longer(cols = c(-metaboliteID), names_to = "full_name", values_to = "metabolite_expression")

single_expression_wide <- single_expression %>%
  filter(expression == "1") %>%
  unite("full_name", c(filename, timepoint)) %>%
  mutate(full_name = str_replace(full_name, "Pig ", "Minipig_")) %>%
  select(full_name, marker, percent_per_marker) %>%
  pivot_wider(names_from = "marker", values_from = "percent_per_marker") %>%
  arrange(full_name) %>%
  column_to_rownames("full_name")

metabolite_wide <- metabolites %>%
  filter(!grepl("Pooled", full_name)) %>%
  pivot_wider(names_from = "metaboliteID", values_from = "metabolite_expression") %>%
  mutate(full_name = str_replace(full_name, "12wks", "Week12"),
         full_name = str_replace(full_name, "30DPI", "D30"))%>%
  arrange(full_name) %>%
  column_to_rownames("full_name")



metabolite_wide

cc(as.matrix(metabolite_wide), as.matrix(single_expression_wide))
```

