---
title: "PCA_clustering"
author: "Amy Fox"
date: "7/6/2021"
output: html_document
---

This is based on the analysis with Bailey 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}
library(readr)
library(dplyr)
library(tidyverse)
library(broom)
```

```{r}
removeZeroVar <- function(df){
  df[, !sapply(df, function(x) min(x) == max(x))]
}
```


Read in data
```{r}
load("../data/flow_predefined_phenotypes.gz")
load("../data/flow_single_expression.gz")
load("../data/flow_fe.gz")

metabolites <- read.csv("../data/peakTable_Minipig_Vaccinated_Unvaccinated_QC.csv") %>%
  dplyr::rename(metaboliteID = X) %>%
  select(metaboliteID, contains("Minipig")) %>%
  pivot_longer(cols = c(-metaboliteID), names_to = "full_name", values_to = "metabolite_expression")

metabolite_wide <- metabolites %>%
  filter(!grepl("Pooled", full_name)) %>%
  pivot_wider(names_from = "metaboliteID", values_from = "metabolite_expression") %>%
  removeZeroVar() %>%
  column_to_rownames("full_name")

match_metabolites <- read.csv("../data/peakTable_Minipig_Vaccinated_Unvaccinated_QC.csv") %>%
  dplyr::rename(metaboliteID = X) 

flow_metab1 <- left_join(flow_predefined_phenotypes, metabolites, by = "full_name") %>%
  rename(percent = marker_percent,
         flow = phenotype,
         vaccine_status = group) 

flow_metab2 <-left_join(flow_fe, metabolites, by = "full_name")%>%
  rename(percent = percentage,
         flow = population)

flow_metab3 <-left_join(flow_single_expression, metabolites, by = "full_name") %>%
  rename(flow = marker)

flow_metab <- rbind(flow_metab1, flow_metab2, flow_metab3) %>%
  mutate(timepoint = str_extract(full_name, "[0-9]*[:alpha:]*$"))

all_flow <- flow_metab %>%
  select(-metaboliteID, -metabolite_expression) %>%
  unique() %>%
  pivot_wider(names_from = flow, values_from = percent)
```

Initial view to show metabolites are correlated
```{r}
# cor1 <- flow_metab   %>%
#   select(full_name, metaboliteID, metabolite_expression) %>%
#   unique() %>%
#    tidyr::pivot_wider(names_from = metaboliteID, 
#                        values_from = metabolite_expression) %>%
#   
#   column_to_rownames("full_name")
# 
# 
#   corr <- round(stats::cor(cor1), 1)
# 
# 
# melted_corr <- format_corr(corr)
#   
# plot_corr(melted_corr) +
#      ggplot2::xlab("Metab") +
#      ggplot2::ylab("Metab") +
#      ggplot2::labs(fill = "Correlation") 
```


PCA and proportion of variance
```{r}
res.pca <- prcomp(metabolite_wide, center = TRUE, scale = TRUE)

res_pca_importance <- summary(res.pca)$importance %>% 
  t() %>% 
  as.data.frame() %>% 
  mutate(PC = factor(1:n()))

res_pca_importance %>% 
  ggplot(aes(x = PC, y = `Proportion of Variance`)) + 
  geom_col() + 
  theme_classic()

PCA_minipig <- res.pca$x %>% 
  as.data.frame() %>% 
  rownames_to_column("name") %>%
  mutate(timepoint = str_extract(name, "[:digit:][:digit:][:alpha:]+")) %>% 
  mutate(vaccine_status = ifelse(name == "Minipig_9947_12wks" | name == "Minipig_9947_30DPI"| name == "Minipig_1817_12wks" | name == "Minipig_6059_12wks" | name == "Minipig_4515_12wks"| name == "Minipig_5273_12wks"| name == "Minipig_1817_30DPI" | name == "Minipig_6059_30DPI" | name == "Minipig_4515_30DPI"| name == "Minipig_5273_30DPI", "vaccinated", "control")) %>%
  mutate(timepoint_vaccine = paste(timepoint," ", vaccine_status)) 

PCA_minipig%>%
  ggplot(aes(x = PC1, y = PC2, color = timepoint_vaccine)) +
  geom_point() + 
  stat_ellipse() +
  theme_classic() +
  labs(x = paste0("PC1: ", round(res_pca_importance$`Proportion of Variance`[1]*100, 1), "%"),
       y = paste0("PC2: ", round(res_pca_importance$`Proportion of Variance`[2]*100, 1), "%")) +
  ggtitle("Metabolite PCA")
```
Correlate PC with flow
```{r}
minipig_PCA <- PCA_minipig %>%
  rename(full_name = name) %>%
  left_join(all_flow, by = c("full_name", "timepoint", "vaccine_status")) %>%
  pivot_longer(c(PC1:PC19), names_to = "PC", values_to = "PC_value") %>%
  pivot_longer(c(CD4_Tcell:SLADQ), names_to = "flow", values_to = "flow_percent")

unique(minipig_PCA$PC)
minipig_PCA %>%
  group_by(PC, flow) %>%
  nest() %>%
  mutate(model = map(data, ~lm(flow_percent ~ PC_value, data = .)),
         summary_model = map(model, tidy)) %>%
unnest(summary_model) %>%
  filter(term != "(Intercept)") %>%
  select(flow, PC, estimate, model) %>%
  mutate(tidy_model = map(model, broom::glance)) %>%
  unnest(tidy_model) %>%
  select(flow, PC, adj.r.squared, p.value, estimate) %>%
  ungroup() %>%
  filter(p.value < 0.05) %>%
  filter(adj.r.squared > .5) %>%
  select(flow,PC, adj.r.squared, p.value) %>%
  unique()


# All with PC2 - pops12, 15, 20, 22, 7, 8, CD172

plot_pick_metab <- function(df, flow_pop, metab_pick, pretty_metab, x_position, yposition1, yposition2) {
  step1 <- df %>%
  filter(flow == flow_pop & PC == metab_pick) %>%
  group_by(PC, flow) %>%
  nest() %>%
  mutate(model = map(data, ~lm(flow_percent ~ PC_value, data = .)),
         summary_model = map(model, tidy)) %>%
unnest(summary_model) %>%
  filter(term != "(Intercept)") %>%
  select(PC, flow, estimate, model) %>%
  mutate(tidy_model = map(model, broom::glance)) %>%
  unnest(tidy_model) %>%
  select(PC, flow, adj.r.squared, p.value, estimate) %>%
  ungroup() %>%
  select(PC, flow, adj.r.squared, p.value) %>%
  unique()

# plot after I bring down the number of metabolites to a reasonable number
df %>%
  filter(flow == flow_pop & PC == metab_pick) %>%
  left_join(step1, by = c("flow", "PC")) %>%
ggplot(aes(x = flow_percent, y = PC_value, color = factor(timepoint))) +
  geom_point(size = 3) +
  geom_smooth(aes(x = flow_percent, y = PC_value), method = "lm", se = FALSE, color = "#3F4788FF") +
  geom_text(aes(x = x_position, y = yposition1, 
                                   label = paste("r^2 == ",
                                                 round(adj.r.squared, 2))), parse = TRUE, color = "black") +
  geom_text(aes(x = x_position, y = yposition2, 
                                   label = paste("p == ",
                                                 signif(p.value, 2))), parse = TRUE, color = "black") +
  ggtitle(pretty_metab) +
  labs(color = "Timepoint", x = paste(flow_pop, "Percentage of Cells"), y = "PC Value", fill = "Timepoint") +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 18),
        title = element_text(size = 18))
}


plot_pick_metab(minipig_PCA, "Pop7", "PC2", "PC2", 2.5, 50, 25) 
plot_pick_metab(minipig_PCA, "Pop8", "PC2", "PC2", 2.5, 50, 25) 
plot_pick_metab(minipig_PCA, "Pop12", "PC2", "PC2", 2.5, 50, 25) 
plot_pick_metab(minipig_PCA, "Pop15", "PC2", "PC2", 0.5, 50, 25) 
plot_pick_metab(minipig_PCA, "Pop20", "PC2", "PC2", 2.5, 50, 25) 
plot_pick_metab(minipig_PCA, "Pop22", "PC2", "PC2", 2.5, 50, 25) 
plot_pick_metab(minipig_PCA, "CD172", "PC2", "PC2", 2.5, 50, 25) 
```

Because PC2 is correlated with flow, figure out which metabolites are contributing to PC2
```{r}

dim(res.pca$rotation)
dim(metabolite_wide)

# confirm that the $rotation is giving us the "importance/weight" of each metabolite
res.pca$rotation[,1] * metabolite_wide[1, ]
res.pca$rotation[ ,1] %*% as.matrix(scale(metabolite_wide[1, ]))

# arrange according to increasing and decreasing importance (note that high + and low - have high importance, those close to 0 have low importance)
res.pca$rotation %>%
  data.frame() %>%
  arrange(PC2)

# plot to see where I should cluster
res.pca$rotation %>%
  data.frame() %>%
  ggplot(aes(x = PC2)) +
  geom_histogram(bins = 50) +
  ylab("Weight of Molecular Features")

# maybe a cluster at >0.02 and < -0.1

# 115 metabolites
cluster1 <- res.pca$rotation %>%
  data.frame() %>%
  filter(PC2 >= 0.02) %>%
  rownames_to_column("metaboliteID") %>%
  mutate(metaboliteID = as.numeric(metaboliteID)) %>%
  select(metaboliteID, PC2)

cluster1_0.3 <- res.pca$rotation %>%
  data.frame() %>%
  filter(PC2 >= 0.03) %>%
  rownames_to_column("metaboliteID") %>%
  mutate(metaboliteID = as.numeric(metaboliteID)) %>%
  select(metaboliteID, PC2)

# 915 metabolites
cluster2_0.2 <- res.pca$rotation %>%
  data.frame() %>%
  filter(PC2 <= -0.02)%>%
  rownames_to_column("metaboliteID") %>%
  mutate(metaboliteID = as.numeric(metaboliteID)) %>%
  select(metaboliteID, PC2)

# 1413 metabolites
cluster2_0.1 <- res.pca$rotation %>%
  data.frame() %>%
  filter(PC2 <= -0.01)%>%
  rownames_to_column("metaboliteID") %>%
  mutate(metaboliteID = as.numeric(metaboliteID)) %>%
  select(metaboliteID, PC2)

# left_join(cluster1, match_metabolites) %>%
#   write.csv("../data/saved_data/PCA/cluster1_metab_list.csv")

# left_join(cluster2_0.2, match_metabolites) %>%
#   write.csv("../data/saved_data/PCA/cluster2_0.2_metab_list.csv")

 # left_join(cluster2_0.1, match_metabolites) %>%
 #   write.csv("../data/saved_data/PCA/cluster2_0.1_metab_list.csv")

 left_join(cluster1_0.3, match_metabolites) %>%
  write.csv("../data/saved_data/PCA/cluster1_0.3_metab_list.csv")
```